"""users table

Revision ID: 4bfc76bfa9b9
Revises: 0a8f2a99c7a3
Create Date: 2019-10-08 15:41:56.083608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfc76bfa9b9'
down_revision = '0a8f2a99c7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('series')
        batch_op.add_column(sa.Column('_series', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('series', sa.TEXT(), nullable=True))
    op.drop_column('user', '_series')
    # ### end Alembic commands ###
