"""ajout du champ notif dans table user

Revision ID: 6a25f2024820
Revises: cf596a31625a
Create Date: 2019-11-11 12:14:45.323999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a25f2024820'
down_revision = 'cf596a31625a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notifications', sa.Binary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notifications')
    # ### end Alembic commands ###
