"""Essai 2

Revision ID: 6ce4d32d1e69
Revises: e080bcee7a8f
Create Date: 2019-10-19 12:59:07.272300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce4d32d1e69'
down_revision = 'e080bcee7a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('movies_grades', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('series_grades', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'series_grades')
    op.drop_column('user', 'movies_grades')
    # ### end Alembic commands ###
