"""Ajout nom series dans bdd

Revision ID: 70319eac0ce9
Revises: 6a25f2024820
Create Date: 2019-11-24 19:36:29.278464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70319eac0ce9'
down_revision = '6a25f2024820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media', sa.Column('media_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_media', 'media_name')
    # ### end Alembic commands ###
