"""Merdier

Revision ID: 7543ead7f043
Revises: 6b96106e3d0d
Create Date: 2019-10-18 11:43:25.263759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7543ead7f043'
down_revision = '6b96106e3d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('movies_grades', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('series_grades', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'series_grades')
    op.drop_column('user', 'movies_grades')
    # ### end Alembic commands ###
