"""Ajout de current_grade

Revision ID: b0ce2c1260fa
Revises: 7543ead7f043
Create Date: 2019-10-19 12:18:15.867087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ce2c1260fa'
down_revision = '7543ead7f043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_grade', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_grade')
    # ### end Alembic commands ###
