"""old fields of user table deleted

Revision ID: cf596a31625a
Revises: eee27859552b
Create Date: 2019-11-10 14:49:27.169530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf596a31625a'
down_revision = 'eee27859552b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('_movies')
        batch_op.drop_column('_series')
        batch_op.drop_column('movies_grades')
        batch_op.drop_column('series_grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('series_grades', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('movies_grades', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('_series', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('_movies', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
