"""Ajout de current_grade

Revision ID: e080bcee7a8f
Revises: b0ce2c1260fa
Create Date: 2019-10-19 12:34:22.283162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e080bcee7a8f'
down_revision = 'b0ce2c1260fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('movies_grades')
        batch_op.drop_column('series_grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('series_grades', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('movies_grades', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
