"""userserie table with grade

Revision ID: eee27859552b
Revises: be927e025a98
Create Date: 2019-11-10 12:41:32.929244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee27859552b'
down_revision = 'be927e025a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media', sa.Column('media_grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_media', 'media_grade')
    # ### end Alembic commands ###
